new syntax

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -85,12 +85,15 @@ jobs:
         id: download_asset
         if: steps.create_or_update_release.outputs.release_id
         run: |
-          response=$(curl -sL https://api.github.com/repos/tajuddin-sonata/repo-may29/releases/latest)
+          response=$(curl -sL https://api.github.com/repos/${{ github.repository }}/releases/latest)
           echo "Response: $response"
           URL=$(echo "$response" | jq -r '.assets[] | select(.name == "app.py") | .browser_download_url')
+          if [[ -z "$URL" || "$URL" == "null" ]]; then
+            echo "App.py asset not found in the release."
+            exit 1
+          fi
           echo "URL: $URL"
           curl -sSL "$URL" --output deployment/app.py
-
 
   deploy:
     needs: release
